export enum ModelQueryMethods {
	Save = 'save',
	Increment = 'increment',
	Remove = 'remove',
	Model = 'model',
	$Where = '$where',
	EnsureIndexes = 'ensureIndexes',
	Find = 'find',
	FindById = 'findById',
	FindOne = 'findOne',
	Count = 'count',
	Distinct = 'distinct',
	Where = 'where',
	FindOneAndUpdate = 'findOneAndUpdate',
	FindByIdAndUpdate = 'findByIdAndUpdate',
	FindOneAndRemove = 'findOneAndRemove',
	FindByIdAndRemove = 'findByIdAndRemove',
	Create = 'create',
	Update = 'update',
	MapReduce = 'mapReduce',
	Aggregate = 'aggregate',
	Base = 'base',
	Collection = 'collection',
	Db = 'db',
	Schema = 'schema',
	ModelName = 'modelName'
};